apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: taqiyeddinedj/redis-node:1.0.0
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_URL
            value: "redis://redis-master:6379"
          - name: REDIS_REPLICAS_URL
            value: "redis://redis-slave:6379"
        resources:
          requests:
            memory: "512Mi"  # Demande minimale de 512 Mo de RAM
            cpu: "500m"      # Demande minimale de 0.5 CPU
          limits:
            memory: "1Gi"    # Limite maximale de 1 Go de RAM
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    app: nodejs-app 
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      name: metrics
      port: 3000
      targetPort: 3000
      nodePort: 32000
